### ISSUE TITLE
You have a license discrepancy. (GNU AGPL =/= GNU GPL)

### ISSUE THREAD

**Issue by Risusama** [Dumpgrah/Public-Ammo-Making#2]
Good evening!

I noticed you have a license discrepancy. You've claimed in the README and on the Steam page that this project is licensed under GNU **A**GPL version 3 (GNU **AFFERO** GENERAL PUBLIC LICENSE). But in the repository, you don't have the GNU AGPL license, instead you have the GNU GPL Version 3 license (GNU GENERAL PUBLIC LICENSE).

I just wanted to bring this to your attention. Thank you, have a great weekend! ^.^

**Comment by Dumpgrah** [comment]
Thank you for the point out

**Comment by Risusama** [comment]
No problem! I see you resolved this with 7be78ed, so I'll close the issue. :)
